<?php
echo "<h4 style=\"text-align: center;\"><a href=\"http://coolapi.uphero.com\">Home</a></h4>\n"; 
echo "<h1 style=\"text-align: center;\"><strong>API documentation</strong></h1>\n"; 
echo "<h2 style=\"text-align: center;\">Random (Fake) Personal Information Generator</h2>\n"; 
echo "<p style=\"text-align: center;\">API endpoint</p>\n"; 
echo "<p style=\"text-align: center;\"><a href=\"http://coolapi.uphero.com/info.json\">coolapi.uphero.com/info.json</a></p>\n"; 
echo "<p style=\"text-align: center;\">&nbsp;</p>\n"; 
echo "<p style=\"text-align: center;\">Example request (python):</p>\n"; 
echo "<p style=\"text-align: center;\"><img src=\"http://coolapi.uphero.com/response2.png\" alt=\"\" width=\"411\" height=\"114\" />&nbsp;</p>\n"; 
echo "<p style=\"text-align: center;\">Example response:</p>\n"; 
echo "<p style=\"text-align: center;\">&nbsp;<img src=\"http://coolapi.uphero.com/request2.png\" alt=\"\" width=\"527\" height=\"267\" /></p>\n"; 
echo "<p style=\"text-align: center;\">Attributes:</p>\n"; 
echo "<p style=\"text-align: center;\">'id' -- Row number</p>\n"; 
echo "<p style=\"text-align: center;\">'title'</p>\n"; 
echo "<p style=\"text-align: center;\">'first_name'</p>\n"; 
echo "<p style=\"text-align: center;\">'last_name'</p>\n"; 
echo "<p style=\"text-align: center;\">'gender'</p>\n"; 
echo "<p style=\"text-align: center;\">'phone'</p>\n"; 
echo "<p style=\"text-align: center;\">'shirt_size'</p>\n"; 
echo "<p style=\"text-align: center;\">'ipv4'</p>\n"; 
echo "<p style=\"text-align: center;\">'ipv6'</p>\n"; 
echo "<p style=\"text-align: center;\">'university'</p>\n"; 
echo "<p style=\"text-align: center;\">'city'</p>\n"; 
echo "<p style=\"text-align: center;\">'country'</p>\n"; 
echo "<p style=\"text-align: center;\">'country_code'</p>\n"; 
echo "<p style=\"text-align: center;\">'lang'</p>\n"; 
echo "<p style=\"text-align: center;\">'state'</p>\n"; 
echo "<p style=\"text-align: center;\">'state_abbrev'</p>\n"; 
echo "<p style=\"text-align: center;\">'postal_code'</p>\n"; 
echo "<p style=\"text-align: center;\">'street_addr'</p>\n"; 
echo "<p style=\"text-align: center;\">'longitude'</p>\n"; 
echo "<p style=\"text-align: center;\">'latitude'</p>\n"; 
echo "<p style=\"text-align: center;\">&nbsp;'timezone'</p>\n"; 
echo "<p style=\"text-align: center;\">'email'</p>\n"; 
echo "<p style=\"text-align: center;\">'avatar'</p>\n"; 
echo "<p style=\"text-align: center;\">'user_agent'</p>\n"; 
echo "<p style=\"text-align: center;\">'username'</p>\n"; 
echo "<p style=\"text-align: center;\">'pass'</p>\n"; 
echo "<p style=\"text-align: center;\">'fav_color'</p>\n"; 
echo "<p style=\"text-align: center;\">'bank_bal'</p>\n"; 
echo "<p style=\"text-align: center;\">'job_title'</p>\n"; 
echo "<p style=\"text-align: center;\">'duns_number'</p>\n"; 
echo "<p style=\"text-align: center;\">'ein' -- Employer ID Number</p>\n"; 
echo "<p style=\"text-align: center;\">'bitcoin_addr'</p>\n"; 
echo "<p style=\"text-align: center;\">'cc' -- Credit Card Number</p>\n"; 
echo "<p style=\"text-align: center;\">'cc_type' -- Credit Card Type</p>\n"; 
echo "<p style=\"text-align: center;\">'ssn' -- Social Security Number</p>\n"; 
echo "<p style=\"text-align: center;\">'friends'</p>\n";
?>
